CREATE TABLE sholat_records (
    id BIGSERIAL PRIMARY KEY,
    record_date DATE NOT NULL UNIQUE,
    subuh_done BOOLEAN NOT NULL DEFAULT FALSE,
    dzuhur_done BOOLEAN NOT NULL DEFAULT FALSE,
    ashar_done BOOLEAN NOT NULL DEFAULT FALSE,
    maghrib_done BOOLEAN NOT NULL DEFAULT FALSE,
    isya_done BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
