CREATE TABLE puasa_records (
    id BIGSERIAL PRIMARY KEY,
    record_date DATE NOT NULL UNIQUE,
    puasa_type TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    sahur_done BOOLEAN NOT NULL DEFAULT FALSE,
    berbuka_done BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
