// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"
)

const getTodayJournalSummary = `-- name: GetTodayJournalSummary :one
SELECT
  EXISTS(
    SELECT 1
    FROM journal_entries
    WHERE entry_date = $1
  ) AS written
`

func (q *Queries) GetTodayJournalSummary(ctx context.Context, entryDate time.Time) (bool, error) {
	row := q.db.QueryRowContext(ctx, getTodayJournalSummary, entryDate)
	var written bool
	err := row.Scan(&written)
	return written, err
}

const getTodayPuasaSummary = `-- name: GetTodayPuasaSummary :one
SELECT
  fast_type,
  completed
FROM puasa_records
WHERE record_date = $1
`

type GetTodayPuasaSummaryRow struct {
	FastType  string `json:"fast_type"`
	Completed bool   `json:"completed"`
}

func (q *Queries) GetTodayPuasaSummary(ctx context.Context, recordDate time.Time) (GetTodayPuasaSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getTodayPuasaSummary, recordDate)
	var i GetTodayPuasaSummaryRow
	err := row.Scan(&i.FastType, &i.Completed)
	return i, err
}

const getTodaySholatSummary = `-- name: GetTodaySholatSummary :one
SELECT
  COALESCE((subuh::int + dzuhur::int + ashar::int + maghrib::int + isya::int), 0)::int AS completed_count
FROM sholat_records
WHERE record_date = $1
`

func (q *Queries) GetTodaySholatSummary(ctx context.Context, recordDate time.Time) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTodaySholatSummary, recordDate)
	var completed_count int32
	err := row.Scan(&completed_count)
	return completed_count, err
}

const getWeeklySportSummary = `-- name: GetWeeklySportSummary :one
SELECT
  COALESCE(COUNT(*) FILTER (WHERE completed), 0)::int AS completed_count,
  COALESCE(SUM(duration_minutes) FILTER (WHERE completed), 0)::int AS completed_minutes
FROM sport_records
WHERE record_date >= $1
  AND record_date < $2
`

type GetWeeklySportSummaryParams struct {
	RecordDate   time.Time `json:"record_date"`
	RecordDate_2 time.Time `json:"record_date_2"`
}

type GetWeeklySportSummaryRow struct {
	CompletedCount   int32 `json:"completed_count"`
	CompletedMinutes int32 `json:"completed_minutes"`
}

func (q *Queries) GetWeeklySportSummary(ctx context.Context, arg GetWeeklySportSummaryParams) (GetWeeklySportSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWeeklySportSummary, arg.RecordDate, arg.RecordDate_2)
	var i GetWeeklySportSummaryRow
	err := row.Scan(&i.CompletedCount, &i.CompletedMinutes)
	return i, err
}

const listContributionDays = `-- name: ListContributionDays :many
SELECT activity_date, SUM(score)::int AS score
FROM (
  SELECT sholat_records.record_date AS activity_date, (subuh::int + dzuhur::int + ashar::int + maghrib::int + isya::int) AS score
  FROM sholat_records
  WHERE sholat_records.record_date >= $1::date AND sholat_records.record_date < $2::date
  UNION ALL
  SELECT puasa_records.record_date AS activity_date, completed::int AS score
  FROM puasa_records
  WHERE puasa_records.record_date >= $1::date AND puasa_records.record_date < $2::date
  UNION ALL
  SELECT sport_records.record_date AS activity_date, completed::int AS score
  FROM sport_records
  WHERE sport_records.record_date >= $1::date AND sport_records.record_date < $2::date
  UNION ALL
  SELECT journal_entries.entry_date AS activity_date, 1 AS score
  FROM journal_entries
  WHERE journal_entries.entry_date >= $1::date AND journal_entries.entry_date < $2::date
) activity
GROUP BY activity_date
ORDER BY activity_date
`

type ListContributionDaysParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
}

type ListContributionDaysRow struct {
	ActivityDate time.Time `json:"activity_date"`
	Score        int32     `json:"score"`
}

func (q *Queries) ListContributionDays(ctx context.Context, arg ListContributionDaysParams) ([]ListContributionDaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listContributionDays, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContributionDaysRow{}
	for rows.Next() {
		var i ListContributionDaysRow
		if err := rows.Scan(&i.ActivityDate, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
