// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance_transactions.sql

package db

import (
	"context"
	"time"
)

const createFinanceTransaction = `-- name: CreateFinanceTransaction :one
INSERT INTO finance_transactions (
  transaction_date,
  transaction_type,
  category,
  amount,
  notes
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, transaction_date, transaction_type, category, amount, notes, created_at, updated_at
`

type CreateFinanceTransactionParams struct {
	TransactionDate time.Time `json:"transaction_date"`
	TransactionType string    `json:"transaction_type"`
	Category        string    `json:"category"`
	Amount          string    `json:"amount"`
	Notes           string    `json:"notes"`
}

func (q *Queries) CreateFinanceTransaction(ctx context.Context, arg CreateFinanceTransactionParams) (FinanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, createFinanceTransaction,
		arg.TransactionDate,
		arg.TransactionType,
		arg.Category,
		arg.Amount,
		arg.Notes,
	)
	var i FinanceTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.TransactionType,
		&i.Category,
		&i.Amount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFinanceTransaction = `-- name: DeleteFinanceTransaction :exec
DELETE FROM finance_transactions
WHERE id = $1
`

func (q *Queries) DeleteFinanceTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFinanceTransaction, id)
	return err
}

const getFinanceTransactionByID = `-- name: GetFinanceTransactionByID :one
SELECT id, transaction_date, transaction_type, category, amount, notes, created_at, updated_at
FROM finance_transactions
WHERE id = $1
`

func (q *Queries) GetFinanceTransactionByID(ctx context.Context, id int64) (FinanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, getFinanceTransactionByID, id)
	var i FinanceTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.TransactionType,
		&i.Category,
		&i.Amount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthlyFinanceSummary = `-- name: GetMonthlyFinanceSummary :one
SELECT
  COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'income'), 0)::numeric(14, 2) AS income,
  COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'expense'), 0)::numeric(14, 2) AS expense
FROM finance_transactions
WHERE transaction_date >= $1
  AND transaction_date < $2
`

type GetMonthlyFinanceSummaryParams struct {
	TransactionDate   time.Time `json:"transaction_date"`
	TransactionDate_2 time.Time `json:"transaction_date_2"`
}

type GetMonthlyFinanceSummaryRow struct {
	Income  string `json:"income"`
	Expense string `json:"expense"`
}

func (q *Queries) GetMonthlyFinanceSummary(ctx context.Context, arg GetMonthlyFinanceSummaryParams) (GetMonthlyFinanceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthlyFinanceSummary, arg.TransactionDate, arg.TransactionDate_2)
	var i GetMonthlyFinanceSummaryRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}

const listFinanceTransactions = `-- name: ListFinanceTransactions :many
SELECT id, transaction_date, transaction_type, category, amount, notes, created_at, updated_at
FROM finance_transactions
ORDER BY transaction_date DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListFinanceTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFinanceTransactions(ctx context.Context, arg ListFinanceTransactionsParams) ([]FinanceTransaction, error) {
	rows, err := q.db.QueryContext(ctx, listFinanceTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceTransaction{}
	for rows.Next() {
		var i FinanceTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.TransactionType,
			&i.Category,
			&i.Amount,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFinanceTransaction = `-- name: UpdateFinanceTransaction :one
UPDATE finance_transactions
SET
  transaction_date = $2,
  transaction_type = $3,
  category = $4,
  amount = $5,
  notes = $6,
  updated_at = now()
WHERE id = $1
RETURNING id, transaction_date, transaction_type, category, amount, notes, created_at, updated_at
`

type UpdateFinanceTransactionParams struct {
	ID              int64     `json:"id"`
	TransactionDate time.Time `json:"transaction_date"`
	TransactionType string    `json:"transaction_type"`
	Category        string    `json:"category"`
	Amount          string    `json:"amount"`
	Notes           string    `json:"notes"`
}

func (q *Queries) UpdateFinanceTransaction(ctx context.Context, arg UpdateFinanceTransactionParams) (FinanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, updateFinanceTransaction,
		arg.ID,
		arg.TransactionDate,
		arg.TransactionType,
		arg.Category,
		arg.Amount,
		arg.Notes,
	)
	var i FinanceTransaction
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.TransactionType,
		&i.Category,
		&i.Amount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
