// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal_entries.sql

package db

import (
	"context"
	"time"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
  entry_date,
  title,
  content,
  mood,
  tags,
  is_private
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, entry_date, title, content, mood, tags, is_private, created_at, updated_at
`

type CreateJournalEntryParams struct {
	EntryDate time.Time `json:"entry_date"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Mood      string    `json:"mood"`
	Tags      string    `json:"tags"`
	IsPrivate bool      `json:"is_private"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, createJournalEntry,
		arg.EntryDate,
		arg.Title,
		arg.Content,
		arg.Mood,
		arg.Tags,
		arg.IsPrivate,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryDate,
		&i.Title,
		&i.Content,
		&i.Mood,
		&i.Tags,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM journal_entries
WHERE id = $1
`

func (q *Queries) DeleteJournalEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournalEntry, id)
	return err
}

const getJournalEntryByID = `-- name: GetJournalEntryByID :one
SELECT id, entry_date, title, content, mood, tags, is_private, created_at, updated_at
FROM journal_entries
WHERE id = $1
`

func (q *Queries) GetJournalEntryByID(ctx context.Context, id int64) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, getJournalEntryByID, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryDate,
		&i.Title,
		&i.Content,
		&i.Mood,
		&i.Tags,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, entry_date, title, content, mood, tags, is_private, created_at, updated_at
FROM journal_entries
ORDER BY entry_date DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListJournalEntriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntry, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.EntryDate,
			&i.Title,
			&i.Content,
			&i.Mood,
			&i.Tags,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal_entries
SET
  entry_date = $2,
  title = $3,
  content = $4,
  mood = $5,
  tags = $6,
  is_private = $7,
  updated_at = now()
WHERE id = $1
RETURNING id, entry_date, title, content, mood, tags, is_private, created_at, updated_at
`

type UpdateJournalEntryParams struct {
	ID        int64     `json:"id"`
	EntryDate time.Time `json:"entry_date"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Mood      string    `json:"mood"`
	Tags      string    `json:"tags"`
	IsPrivate bool      `json:"is_private"`
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRowContext(ctx, updateJournalEntry,
		arg.ID,
		arg.EntryDate,
		arg.Title,
		arg.Content,
		arg.Mood,
		arg.Tags,
		arg.IsPrivate,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.EntryDate,
		&i.Title,
		&i.Content,
		&i.Mood,
		&i.Tags,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
