// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type FinanceTransaction struct {
	ID              int64     `json:"id"`
	TransactionDate time.Time `json:"transaction_date"`
	TransactionType string    `json:"transaction_type"`
	Category        string    `json:"category"`
	Amount          string    `json:"amount"`
	Notes           string    `json:"notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type JournalEntry struct {
	ID        int64     `json:"id"`
	EntryDate time.Time `json:"entry_date"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Mood      string    `json:"mood"`
	Tags      string    `json:"tags"`
	IsPrivate bool      `json:"is_private"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PuasaRecord struct {
	ID         int64     `json:"id"`
	RecordDate time.Time `json:"record_date"`
	FastType   string    `json:"fast_type"`
	Completed  bool      `json:"completed"`
	Sahur      bool      `json:"sahur"`
	Iftar      bool      `json:"iftar"`
	Notes      string    `json:"notes"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type SholatRecord struct {
	ID                int64     `json:"id"`
	RecordDate        time.Time `json:"record_date"`
	Subuh             bool      `json:"subuh"`
	Dzuhur            bool      `json:"dzuhur"`
	Ashar             bool      `json:"ashar"`
	Maghrib           bool      `json:"maghrib"`
	Isya              bool      `json:"isya"`
	CongregationCount int32     `json:"congregation_count"`
	Notes             string    `json:"notes"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type SportRecord struct {
	ID              int64     `json:"id"`
	RecordDate      time.Time `json:"record_date"`
	SportType       string    `json:"sport_type"`
	DurationMinutes int32     `json:"duration_minutes"`
	Completed       bool      `json:"completed"`
	Notes           string    `json:"notes"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
