// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: puasa_records.sql

package db

import (
	"context"
	"time"
)

const createPuasaRecord = `-- name: CreatePuasaRecord :one
INSERT INTO puasa_records (
  record_date,
  fast_type,
  completed,
  sahur,
  iftar,
  notes
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, record_date, fast_type, completed, sahur, iftar, notes, created_at, updated_at
`

type CreatePuasaRecordParams struct {
	RecordDate time.Time `json:"record_date"`
	FastType   string    `json:"fast_type"`
	Completed  bool      `json:"completed"`
	Sahur      bool      `json:"sahur"`
	Iftar      bool      `json:"iftar"`
	Notes      string    `json:"notes"`
}

func (q *Queries) CreatePuasaRecord(ctx context.Context, arg CreatePuasaRecordParams) (PuasaRecord, error) {
	row := q.db.QueryRowContext(ctx, createPuasaRecord,
		arg.RecordDate,
		arg.FastType,
		arg.Completed,
		arg.Sahur,
		arg.Iftar,
		arg.Notes,
	)
	var i PuasaRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.FastType,
		&i.Completed,
		&i.Sahur,
		&i.Iftar,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePuasaRecord = `-- name: DeletePuasaRecord :exec
DELETE FROM puasa_records
WHERE id = $1
`

func (q *Queries) DeletePuasaRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePuasaRecord, id)
	return err
}

const getPuasaRecordByDate = `-- name: GetPuasaRecordByDate :one
SELECT id, record_date, fast_type, completed, sahur, iftar, notes, created_at, updated_at
FROM puasa_records
WHERE record_date = $1
`

func (q *Queries) GetPuasaRecordByDate(ctx context.Context, recordDate time.Time) (PuasaRecord, error) {
	row := q.db.QueryRowContext(ctx, getPuasaRecordByDate, recordDate)
	var i PuasaRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.FastType,
		&i.Completed,
		&i.Sahur,
		&i.Iftar,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPuasaRecordByID = `-- name: GetPuasaRecordByID :one
SELECT id, record_date, fast_type, completed, sahur, iftar, notes, created_at, updated_at
FROM puasa_records
WHERE id = $1
`

func (q *Queries) GetPuasaRecordByID(ctx context.Context, id int64) (PuasaRecord, error) {
	row := q.db.QueryRowContext(ctx, getPuasaRecordByID, id)
	var i PuasaRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.FastType,
		&i.Completed,
		&i.Sahur,
		&i.Iftar,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPuasaRecords = `-- name: ListPuasaRecords :many
SELECT id, record_date, fast_type, completed, sahur, iftar, notes, created_at, updated_at
FROM puasa_records
ORDER BY record_date DESC
LIMIT $1 OFFSET $2
`

type ListPuasaRecordsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPuasaRecords(ctx context.Context, arg ListPuasaRecordsParams) ([]PuasaRecord, error) {
	rows, err := q.db.QueryContext(ctx, listPuasaRecords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PuasaRecord{}
	for rows.Next() {
		var i PuasaRecord
		if err := rows.Scan(
			&i.ID,
			&i.RecordDate,
			&i.FastType,
			&i.Completed,
			&i.Sahur,
			&i.Iftar,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePuasaRecord = `-- name: UpdatePuasaRecord :one
UPDATE puasa_records
SET
  fast_type = $2,
  completed = $3,
  sahur = $4,
  iftar = $5,
  notes = $6,
  updated_at = now()
WHERE id = $1
RETURNING id, record_date, fast_type, completed, sahur, iftar, notes, created_at, updated_at
`

type UpdatePuasaRecordParams struct {
	ID        int64  `json:"id"`
	FastType  string `json:"fast_type"`
	Completed bool   `json:"completed"`
	Sahur     bool   `json:"sahur"`
	Iftar     bool   `json:"iftar"`
	Notes     string `json:"notes"`
}

func (q *Queries) UpdatePuasaRecord(ctx context.Context, arg UpdatePuasaRecordParams) (PuasaRecord, error) {
	row := q.db.QueryRowContext(ctx, updatePuasaRecord,
		arg.ID,
		arg.FastType,
		arg.Completed,
		arg.Sahur,
		arg.Iftar,
		arg.Notes,
	)
	var i PuasaRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.FastType,
		&i.Completed,
		&i.Sahur,
		&i.Iftar,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
