// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sholat_records.sql

package db

import (
	"context"
	"time"
)

const createSholatRecord = `-- name: CreateSholatRecord :one
INSERT INTO sholat_records (
  record_date,
  subuh,
  dzuhur,
  ashar,
  maghrib,
  isya,
  congregation_count,
  notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, record_date, subuh, dzuhur, ashar, maghrib, isya, congregation_count, notes, created_at, updated_at
`

type CreateSholatRecordParams struct {
	RecordDate        time.Time `json:"record_date"`
	Subuh             bool      `json:"subuh"`
	Dzuhur            bool      `json:"dzuhur"`
	Ashar             bool      `json:"ashar"`
	Maghrib           bool      `json:"maghrib"`
	Isya              bool      `json:"isya"`
	CongregationCount int32     `json:"congregation_count"`
	Notes             string    `json:"notes"`
}

func (q *Queries) CreateSholatRecord(ctx context.Context, arg CreateSholatRecordParams) (SholatRecord, error) {
	row := q.db.QueryRowContext(ctx, createSholatRecord,
		arg.RecordDate,
		arg.Subuh,
		arg.Dzuhur,
		arg.Ashar,
		arg.Maghrib,
		arg.Isya,
		arg.CongregationCount,
		arg.Notes,
	)
	var i SholatRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.Subuh,
		&i.Dzuhur,
		&i.Ashar,
		&i.Maghrib,
		&i.Isya,
		&i.CongregationCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSholatRecord = `-- name: DeleteSholatRecord :exec
DELETE FROM sholat_records
WHERE id = $1
`

func (q *Queries) DeleteSholatRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSholatRecord, id)
	return err
}

const getSholatRecordByDate = `-- name: GetSholatRecordByDate :one
SELECT id, record_date, subuh, dzuhur, ashar, maghrib, isya, congregation_count, notes, created_at, updated_at
FROM sholat_records
WHERE record_date = $1
`

func (q *Queries) GetSholatRecordByDate(ctx context.Context, recordDate time.Time) (SholatRecord, error) {
	row := q.db.QueryRowContext(ctx, getSholatRecordByDate, recordDate)
	var i SholatRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.Subuh,
		&i.Dzuhur,
		&i.Ashar,
		&i.Maghrib,
		&i.Isya,
		&i.CongregationCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSholatRecordByID = `-- name: GetSholatRecordByID :one
SELECT id, record_date, subuh, dzuhur, ashar, maghrib, isya, congregation_count, notes, created_at, updated_at
FROM sholat_records
WHERE id = $1
`

func (q *Queries) GetSholatRecordByID(ctx context.Context, id int64) (SholatRecord, error) {
	row := q.db.QueryRowContext(ctx, getSholatRecordByID, id)
	var i SholatRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.Subuh,
		&i.Dzuhur,
		&i.Ashar,
		&i.Maghrib,
		&i.Isya,
		&i.CongregationCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSholatRecords = `-- name: ListSholatRecords :many
SELECT id, record_date, subuh, dzuhur, ashar, maghrib, isya, congregation_count, notes, created_at, updated_at
FROM sholat_records
ORDER BY record_date DESC
LIMIT $1 OFFSET $2
`

type ListSholatRecordsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSholatRecords(ctx context.Context, arg ListSholatRecordsParams) ([]SholatRecord, error) {
	rows, err := q.db.QueryContext(ctx, listSholatRecords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SholatRecord{}
	for rows.Next() {
		var i SholatRecord
		if err := rows.Scan(
			&i.ID,
			&i.RecordDate,
			&i.Subuh,
			&i.Dzuhur,
			&i.Ashar,
			&i.Maghrib,
			&i.Isya,
			&i.CongregationCount,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSholatRecord = `-- name: UpdateSholatRecord :one
UPDATE sholat_records
SET
  subuh = $2,
  dzuhur = $3,
  ashar = $4,
  maghrib = $5,
  isya = $6,
  congregation_count = $7,
  notes = $8,
  updated_at = now()
WHERE id = $1
RETURNING id, record_date, subuh, dzuhur, ashar, maghrib, isya, congregation_count, notes, created_at, updated_at
`

type UpdateSholatRecordParams struct {
	ID                int64  `json:"id"`
	Subuh             bool   `json:"subuh"`
	Dzuhur            bool   `json:"dzuhur"`
	Ashar             bool   `json:"ashar"`
	Maghrib           bool   `json:"maghrib"`
	Isya              bool   `json:"isya"`
	CongregationCount int32  `json:"congregation_count"`
	Notes             string `json:"notes"`
}

func (q *Queries) UpdateSholatRecord(ctx context.Context, arg UpdateSholatRecordParams) (SholatRecord, error) {
	row := q.db.QueryRowContext(ctx, updateSholatRecord,
		arg.ID,
		arg.Subuh,
		arg.Dzuhur,
		arg.Ashar,
		arg.Maghrib,
		arg.Isya,
		arg.CongregationCount,
		arg.Notes,
	)
	var i SholatRecord
	err := row.Scan(
		&i.ID,
		&i.RecordDate,
		&i.Subuh,
		&i.Dzuhur,
		&i.Ashar,
		&i.Maghrib,
		&i.Isya,
		&i.CongregationCount,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
